language: go
go:
  - 1.7
branches:
  only:
  - master
before_install:
  - nvm install node
  - nvm use node
  - npm install -g firebase-tools
install:
  - go get -u -v igthub.com/spf13/hugo
script:
  - hugo
after_success:
  - firebase --token $FIREBSE_TOKEN --project sh4869-blog   deploy
