language: go
branches:
  only:
  - master
before_install:
  - nvm install node
  - nvm use node
  - npm install -g firebase-tools
install:
  - go get -u -v github.com/spf13/hugo
script:
  - hugo
after_success:
  - firebase --token $FIREBASE_TOKEN --project sh4869-blog deploy
