language: go
branches:
  only:
  - master
before_install:
  - nvm install node
  - nvm use node
  - npm install -g firebase-tools
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
script:
  - hugo
after_success:
  - firebase --token $FIREBASE_TOKEN --project sh4869-blog deploy
