baseurl = "http://blog.sh4869.net/"
languageCode = "ja"
title = "Laboratory of Scarlet"
author = "sh4869"
googleanalytics = "UA-12345678-9"
theme = "hugo_theme_beg"

[permalinks]
  post = "/posts/:year/:month/:day/:filename/"

[outputFormats.RSS]
  baseName = "feed"