baseurl = "https://blog.sh4869.net/"
languageCode = "ja"
title = "Report of Scarlet"
author = "sh4869"
googleanalytics = "UA-46319605-19"
theme = "heroshow"
hasCJKLanguage = true
pygmentsUseClasses = true
summaryLength = 200
disqusShortname = "blog-sh4869-net"
enableGitInfo = true

[markup]
  defaultMarkdownHandler = "blackfriday"

[permalinks]
  post = "/:slug/:year/:month/:day/:filename/"

[outputFormats.RSS]
  baseName = "feed"

[params]
description = "@sh4869 tech blog | 猩々緋報"
icon = "/images/blog-icon.png"
repo = "https://github.com/sh4869/blog"

[[menu.main]]
name = "About"
url = "http://sh4869.net"
weight = 3

[[menu.main]]
name = "RSS"
url = "https://blog.sh4869.net/feed.xml"
weight = 4

