baseurl = "https://blog.sh4869.net/"
languageCode = "ja"
title = "Laboratory of Scarlet"
author = "sh4869"
googleanalytics = "UA-46319605-19"
theme = "heroshow"
hasCJKLanguage = true
pygmentsUseClasses = true
summaryLength = 200
disqusShortname = "blog-sh4869-net"

[markup]
  defaultMarkdownHandler = "blackfriday"

[permalinks]
  post = "/:slug/:year/:month/:day/:filename/"

[outputFormats.RSS]
  baseName = "feed"

[params]
custom_css = ["css/custom.css"]
description = "@sh4869 tech blog"
icon = "/images/blog-icon.png"

[[menu.main]]
name = "About"
url = "http://sh4869.net"
weight = 3

