baseurl = "https://blog.sh4869.net/"
languageCode = "ja"
title = "Laboratory of Scarlet"
author = "sh4869"
googleanalytics = "UA-46319605-19"
theme = "heroshow"
hasCJKLanguage = true
pygmentsUseClasses = true

[markup]
  defaultMarkdownHandler = "blackfriday"

[permalinks]
  post = "/:slug/:year/:month/:day/:filename/"

[outputFormats.RSS]
  baseName = "feed"

[params]
disqusShortname = "blog-sh4869-net"
custom_css = ["css/custom.css"]
description = "Work is the best antidote to sorrow, my dear Watson"
icon = "/images/blog-icon.png"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1

[[menu.main]]
name = "Tags"
url  = "/tags/"
weight = 2

[[menu.main]]
name = "About"
url = "http://sh4869.net"
weight = 3

