baseurl = "https://blog.sh4869.net/"
languageCode = "ja"
title = "Laboratory of Scarlet"
author = "sh4869"
googleanalytics = "UA-46319605-19"
theme = "heroshow"
hasCJKLanguage = true

[permalinks]
  post = "/:slug/:year/:month/:day/:filename/"

[outputFormats.RSS]
  baseName = "feed"

[params]
disqusShortname = "blog-sh4869-net"
custom_css = ["css/custom.css"]

[[menu.main]]
name = "sh4869.net"
url = "http://sh4869.net"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "Tags"
url  = "/tags/"
weight = 3

