name: Build and Deploy

on:
  push:
    branches: [ master ]
jobs:
  deploy:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.1'
      - name: Build
        run: hugo --minify
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
            args: deploy --token $FIREBASE_TOKEN --only hosting --project sh4869-blog
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Slack Notification
        if: success()
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_HOOKS }}
        with:
          text: "[BLOG] DEPLOY COMPLETE"
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  }
                ]
              }
            ]
